markdown: kramdown
highlighter: rouge
permalink: /archive/:year/:title.html
rdiscount:
  extensions: [smart]

name: Shashank Mehta
url: http://shashankmehta.in
description: Heading product for RazorpayX, building the future of business banking. Early bird (#7) at @Razorpay. Forever hoarse throat thanks to ManUtd.
twitter: shashankmehta05
github: leostatic
gravatar_url: http://www.gravatar.com/avatar/91d05b8aab2671b4abc8a8c76435bf5a

googleplus_user: '109764126807838271120'
googleplus_hidden: false

google_analytics_tracking_id: UA-32545112-1

plugins:
  - jekyll-redirect-from
